# XML_SRCDIR defines the place where XMLs present.
XML_SRCDIR := .

# XML_INDEX_NAME defines the main XML index page without extension.
XML_INDEX_NAME := index

# MM_SRC is FreeMind .mm filename
MM_SRC := mindmap/docbook.mm

